import * as FileSystem from 'expo-file-system/legacy';
import { base_url } from '../config';
import { LOGO_BASE64_DATA_URI } from '../assets/logoBase64';

const BACKEND_URL = (base_url || '').replace(/\/api\/?$/, '');

// ── Company Logo ────────────────────────────────────────────────────────────
// The Company Logo is a fixed brand asset — it is NEVER sourced from MongoDB,
// Cloudinary, or any API. It always renders from assets/logo.png.
//
// It is embedded as a base64 string at BUILD TIME (see assets/logoBase64.js,
// generated by scripts/generateLogoBase64.js) rather than resolved at RUNTIME
// via the Expo asset system (Asset.fromModule/downloadAsync). This is a
// deliberate, permanent fix: runtime asset resolution goes through a native
// bridge (Metro asset registry -> native module -> filesystem) that has
// proven unreliable specifically in release APK builds, even though the
// exact same code works in Expo Go / dev. A base64 string baked directly
// into the JS bundle has NO native resolution step and NO environment-
// dependent code path at all — it is loaded identically by every JS engine
// in every build type (dev, Expo Go, debug APK, release APK) because it's
// just a JavaScript string literal, not a file reference.
//
// For the native <Image> component elsewhere in the app (e.g. the Home
// screen header, Kadai Profile preview), keep using the ordinary bundled
// asset — that rendering path is unaffected and require()-based Image
// resolution is not the part that was broken.
export const LOGO_ASSET = require('../assets/logo.png');

const isValidDataUri = (value) =>
  typeof value === 'string' && value.startsWith('data:image/') && value.length > 100;

// Kept async/Promise-returning (even though the value is available
// synchronously) so every existing call site — which already does
// `await getLogoDataUri()` or `.then(...)` before generating a PDF — keeps
// working unchanged and still genuinely waits for a validated result.
export const getLogoDataUri = async () => {
  console.log('[Logo] source: assets/logoBase64.js (build-time constant, no runtime asset resolution)');
  if (!isValidDataUri(LOGO_BASE64_DATA_URI)) {
    console.error(
      '[Logo] LOGO_BASE64_DATA_URI is missing or malformed. Regenerate it with:',
      'npm run generate:logo'
    );
    return '';
  }
  console.log(`[Logo] loaded OK — ${LOGO_BASE64_DATA_URI.length} base64 chars, ready immediately, safe to generate PDF now`);
  return LOGO_BASE64_DATA_URI;
};

// ── Authorized Signature ────────────────────────────────────────────────────
// Unlike the logo, the signature is still an Admin-managed upload stored in
// MongoDB (ShopProfile.signatureUrl / signatureBase64).
//
// MongoDB Atlas is a persistent, shared cloud database, but the backend's
// local disk (where signatureUrl-hosted files live) is NOT persistent on
// most hosts (e.g. Render wipes local disk on every restart/redeploy/cold
// start). So signatureBase64 — sitting right there in the same MongoDB
// document — is the reliable source; the URL is a best-effort optimization
// only, tried second, and skipped entirely once base64 is available.
const resolveSignatureDataUri = async (url, base64) => {
  if (base64) {
    console.log(`[Signature] using base64 stored on profile (${base64.length} chars)`);
    return base64.startsWith('data:') ? base64 : `data:image/png;base64,${base64}`;
  }
  if (url) {
    const fullUrl = url.startsWith('http') ? url : `${BACKEND_URL}${url}`;
    console.log('[Signature] no base64 on profile — resolving from URL:', fullUrl);
    try {
      const cacheFile = `${FileSystem.cacheDirectory}shop_signature_cache.png`;
      const { uri: downloadedUri, status } = await FileSystem.downloadAsync(fullUrl, cacheFile);
      // downloadAsync does NOT throw on HTTP error status codes (404/500/etc) —
      // it happily writes the error page body to disk and resolves normally.
      // Without this check a dead URL would silently "succeed" with a page of
      // HTML masquerading as image bytes instead of failing visibly.
      if (status < 200 || status >= 300) {
        console.error(`[Signature] URL returned HTTP ${status} — not a valid image:`, fullUrl);
      } else {
        const b64 = await FileSystem.readAsStringAsync(downloadedUri, { encoding: FileSystem.EncodingType.Base64 });
        if (b64) {
          console.log(`[Signature] loaded OK from URL (${b64.length} base64 chars)`);
          return `data:image/png;base64,${b64}`;
        }
        console.warn('[Signature] download succeeded but file was empty:', fullUrl);
      }
    } catch (error) {
      console.error('[Signature] failed to load from URL:', fullUrl, '-', error?.message || error);
    }
  }
  console.log('[Signature] no image uploaded — hiding image area');
  return '';
};

export const getSignatureDataUri = (profile) => {
  console.log('[Signature] MongoDB profile fields:', {
    signatureUrl: profile?.signatureUrl || '(empty)',
    signatureBase64: profile?.signatureBase64 ? `(set, ${profile.signatureBase64.length} chars)` : '(empty)',
  });
  return resolveSignatureDataUri(profile?.signatureUrl, profile?.signatureBase64);
};
